language: node_js
sudo: false
node_js:
- '6.1'
script:
- npm run ci
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: fAIjDTQbNJYQo/7W9SfrXf+4FyyV2cZWxoIB00fEMfPRXMs56eTxdq/XLBSg+F5jc++rLP5HLfkWjEv5F6oBOxLYlNzyVFChK9DJP5EtBKD0Vt74niDMuPE2BdhtvupO9AUpARpyYWvb+pc00X2uj6v8GR1xtbIXbhDAoS/bN2aqgXyKY6ahD0wajH2wnI5NB7b5Wv1eFAYq7BRW6rOuKvV1JKiQDwEpQY5KqNsRBq9Y0deAK2o/jjkX56kpJk+3DjjkMF8o74C/rtitCu2Kih8l/ZKiOhZlEOtcs8NOBZ9MFCFI5NUgY02uoiqXq2FoCjGBbTd6uo88TQ29EuOUArTnhUthEI2YFi3+7jgi78vCvzS53+/G1eJsYTOm+6kwuddFhVT9ZTrO9NBYaDV8vXbpEcHPYv4fn5uSQaqmQX81kve47ussT7ijrh+7uM+a4gCso4MZ5H7l0fBkwy8bGpi0mLGYMS7CvCYhib056AcD8VyvW/bwq2y5dk3b+diqJbh96drFR6pH/mGGWd4T33Sr4RcbFr7+X1782Yq9Co7P2hlNPvjqylEFGxHJIW0j/l0yEwkFRM6zbAK08cULWmSm3QGSv6fd6rnADvHvbjxwNtBC0IVng4tN3498QcNn1l6pmQcT4LtAG8fHV8ddTKl5ApNlU1dl8NeMKpFq25c=
  skip_cleanup: true
  on:
    branch: v0
    tags: true
