language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run ci
- chmod 777 ./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh
- export TEST_GROUP=desktop-regression
- ./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh
- npm run gh-pages
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: TliCWs76ftZKxuJPyl3y5lFCSKnH2Y+T8wtMbgRAx9JR61bdEmIEKuNwRDnPMthIbDm0UfWdPcnVCRqn/aVnrOOAX7rV7Pk5KNCEwsjx5px30eCm4ERtBMVYb16vtFhhCfYDChfXqx8ZhvmiceX/ZNwg07qCZBb6aKytETd7GubJWDtn8w4ogt6l4WwgJvCq3/xuveGfD3XOoa1sjN8th3OsfVK7v5d6lMso1juVWaoKbCicJHxL2+O111wH0LxjmAW/RYqCVuqEjkxpwN9iJG7fQ3zhrwe7De6AWQxwQwdHDPzXNj7W0NFw9OyjLBegTaZ8JWtFxvUlvHmg/6CnnP9oAFNmvL+58UF0Emu/YVlhKro8eCCGDXXcZIx0fWpR7GEkmoAwzusVcxOeGchjBp1fLfBD2kdMRpUshn5TtjcfXhw4CFWv4A41cNgkjf7t2FKLMH0siaVUB5VP+CGMhocLDjcKSxrD8vJBs2yVpPxDL/PH6xGRIyK0mKtVsIVtejjJKKp987WoIpYd3fVnTI+k9+ICTtf+9BsM5sPJMlTNtJtb28o2yT7DihYsP3l044HYeQD1WA0M22HJ2JJurb7tMx2CoYtPU4NA7FRgCf/M2phUl96DHhbvvk5U1ijyIa2pBGz6ptIc8D5CpYiBreFi2xK0ZpgYMecvL5DKhNs=
  skip_cleanup: true
  on:
    branch: v0
    tags: true
env:
  global:
    secure: J1PS8zDaEQKCJYcsb9Y1rlKWq1zLxs4l+Kuyx4+0zD1OGDXGlJ1ncub3bbkwvohowJ5L7EJ8LGBAVJKvWz2NgXhvJe0Pz1GE4dP0AMk3L//H8f9tITNk4WEzJi9Yc+gaAAcTJO8fgALo+25kvVf0HDtppFPlvB2IawULuttGjEBcXOrpU/GxeNAOeuB6Akvk7dRIzJ6X/GJk4oiTCnZ/03olyHwggjsyd2PipKo31ktJQ9PQzPhpupRmo/Jn46PQ2AuBtLF1TUxzPLwhkxRsNYnIfZduNhmOfMkZ4+bNr8eyxPI2wJUGJhw0/g7diYxsVarux0MTv7L7WdIkWRQat9YLmlTceX+W6TNEsuzWDAWrdTQKVYGgz9CYJD1PoccY+KtXxbND0o7Fog+mH8zgwCOqKTQtb/Ak9VSm6ZfSwQn2uObg38Ml0O2+pe07Wom7EAmfBTSXlqiU3C1oGOR/gP5K3pUsvAtqr+6TQZvCyCcZVjbha3LuTSG4wNpsOCkQSxi0kGB5LSren/tGgc4+Y0A+Wo667nDiGeQ5iNZabXMeoqmd8iU7z8zmqhtzmX7yI/qxNxV+/9G1CFbrgf3K21mqLAwXv0MtoMfpE9wDSHIxRLnCdaDKo009Zjd9ANC3LM0bHXf39aTkzT27OOj/eTFZHK1gLikKGhszd6uY1Ik=
