language: node_js
sudo: false
node_js:
- 4
- 6
script:
# - npm run ci
# - chmod 777 ./test/shell_scripts/run_tests.sh
# - ./test/shell_scripts/run_tests.sh

deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: I7MhEd++LqQyxQcivH7thVwazRHmV1By4TzjdKicHHur4qHaQzjiq5a5pM7LtPzrDbgxZapBwA/9okz13iSGeqG+/Nks8Nc2ac1wGOpnewnOSNnCw4e8tJT7Ug88s5cdcIfKeA0GhzUrRie5xEADBk1+9T+UXUujGiUNYcVftmqwV2xEHeE2FqjLGat0OLLx33llpM7ppt3pC00W7dRz/1IEY1Ov/U4lSqEqlppGfbLhi3X7SrgK66eqAiBS21lHUc2EF+/9Z5cebYjVMB6Wlbb6DcbYsm2rUEXiNmKu23P89yOBgLx9VEImDnyfOAfwGXX0H8fHgDXXC0dQboC9pCcBMbe6v4PH9zg0qs2pfUbsBTEX8m376dI1jm8RZhwVAQ0o1wsqLe0d11+p9hEROp0vs4Vgi7Uern7Fzyvpsi/b/ZpxIxbldqbhyb9GVgcrepfBvG3OFCVxNTcjYjyUjn1BATHZA9MdFQgsZTf//AjsbuQp6KGEPzCUTRLlzc5TvJ6LwsPw5Kvbj5hTLUblcgbPNTQH31vcHxkqWaQ8cnwSFinjiKJtdYn5SCHHpMLxdGSg2Pr16mNP+uByf6/A7tpb304TOJGzv3WQdZrwaOTG0KFRIGb4Lurjn+sZXzIsKkboUsJDijdnuxOLCl5a7aPT0JfP+I2IR0GHcAdpG0M=
  skip_cleanup: true
  on:
    branch: v0
    tags: true
env:
  global:
    secure: J1PS8zDaEQKCJYcsb9Y1rlKWq1zLxs4l+Kuyx4+0zD1OGDXGlJ1ncub3bbkwvohowJ5L7EJ8LGBAVJKvWz2NgXhvJe0Pz1GE4dP0AMk3L//H8f9tITNk4WEzJi9Yc+gaAAcTJO8fgALo+25kvVf0HDtppFPlvB2IawULuttGjEBcXOrpU/GxeNAOeuB6Akvk7dRIzJ6X/GJk4oiTCnZ/03olyHwggjsyd2PipKo31ktJQ9PQzPhpupRmo/Jn46PQ2AuBtLF1TUxzPLwhkxRsNYnIfZduNhmOfMkZ4+bNr8eyxPI2wJUGJhw0/g7diYxsVarux0MTv7L7WdIkWRQat9YLmlTceX+W6TNEsuzWDAWrdTQKVYGgz9CYJD1PoccY+KtXxbND0o7Fog+mH8zgwCOqKTQtb/Ak9VSm6ZfSwQn2uObg38Ml0O2+pe07Wom7EAmfBTSXlqiU3C1oGOR/gP5K3pUsvAtqr+6TQZvCyCcZVjbha3LuTSG4wNpsOCkQSxi0kGB5LSren/tGgc4+Y0A+Wo667nDiGeQ5iNZabXMeoqmd8iU7z8zmqhtzmX7yI/qxNxV+/9G1CFbrgf3K21mqLAwXv0MtoMfpE9wDSHIxRLnCdaDKo009Zjd9ANC3LM0bHXf39aTkzT27OOj/eTFZHK1gLikKGhszd6uY1Ik=
